fix

diff --git a/.github/workflows/bat.yml b/.github/workflows/bat.yml
--- a/.github/workflows/bat.yml
+++ b/.github/workflows/bat.yml
@@ -118,11 +118,6 @@ jobs:
         with:
           source-folder: sample
           code-coverage-metric-level: mcdc
-          startup-options: -logfile test.log
-      - name: Verify no coverage summary for Test Case 1
-        run: |
-          ! grep -q "added the coverage details" test.log
-        shell: bash
       - name: Perform 'setup-matlab' with MATLAB Test
         uses: matlab-actions/setup-matlab@v3
         with:
@@ -144,11 +139,6 @@ jobs:
           use-parallel: true
           output-detail: Detailed
           logging-level: Detailed
-          startup-options: -logfile test.log
-      - name: Verify no coverage summary for Test Case 1
-        run: |
-          ! grep -q "added the coverage details" test.log
-        shell: bash
       - name: Run MATLAB Tests # Test Case 3: With MATLAB Test, and only code-coverage-metric-level option, view is shown.
         uses: ./
         with:
@@ -157,5 +147,13 @@ jobs:
           startup-options: -logfile test.log
       - name: Verify coverage summary view is generated
         run: |
-          grep "added the coverage details" test.log
+          if [ ! -f "$GITHUB_STEP_SUMMARY" ]; then
+            echo "Step summary file not found"
+            exit 1
+          fi
+          echo "Step summary file found"
+          cat "$GITHUB_STEP_SUMMARY"
+
+          # Check for content expected in the coverage summary
+          grep -q "Coverage" "$GITHUB_STEP_SUMMARY"
         shell: bash
